# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'solvent.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QComboBox, QDateEdit,
    QDateTimeEdit, QFrame, QLabel, QLineEdit,
    QMainWindow, QPlainTextEdit, QPushButton, QScrollArea,
    QSizePolicy, QTabWidget, QTextEdit, QWidget)

class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.setEnabled(True)
        Main.resize(500, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        Main.setMinimumSize(QSize(500, 720))
        Main.setMaximumSize(QSize(500, 720))
        Main.setAutoFillBackground(False)
        self.centralwidget = QWidget(Main)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QSize(500, 720))
        self.centralwidget.setMaximumSize(QSize(500, 720))
        self.Tabs = QTabWidget(self.centralwidget)
        self.Tabs.setObjectName(u"Tabs")
        self.Tabs.setEnabled(True)
        self.Tabs.setGeometry(QRect(0, 0, 501, 721))
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy1)
        self.Tabs.setTabPosition(QTabWidget.North)
        self.Tabs.setTabShape(QTabWidget.Rounded)
        self.Tabs.setIconSize(QSize(0, 0))
        self.Tabs.setElideMode(Qt.ElideNone)
        self.Tabs.setUsesScrollButtons(True)
        self.Tabs.setDocumentMode(True)
        self.Tabs.setTabsClosable(False)
        self.Tabs.setMovable(False)
        self.Tabs.setTabBarAutoHide(False)
        self.customertab = QWidget()
        self.customertab.setObjectName(u"customertab")
        self.customertab.setMaximumSize(QSize(500, 16777215))
        self.informationBrowser = QTextEdit(self.customertab)
        self.informationBrowser.setObjectName(u"informationBrowser")
        self.informationBrowser.setGeometry(QRect(250, 30, 250, 659))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.informationBrowser.sizePolicy().hasHeightForWidth())
        self.informationBrowser.setSizePolicy(sizePolicy2)
        self.informationBrowser.setMaximumSize(QSize(250, 16777215))
        font = QFont()
        font.setPointSize(13)
        self.informationBrowser.setFont(font)
        self.informationBrowser.setContextMenuPolicy(Qt.NoContextMenu)
        self.informationBrowser.setFrameShape(QFrame.NoFrame)
        self.informationBrowser.setFrameShadow(QFrame.Plain)
        self.informationBrowser.setReadOnly(True)
        self.customerRefreshButton = QPushButton(self.customertab)
        self.customerRefreshButton.setObjectName(u"customerRefreshButton")
        self.customerRefreshButton.setGeometry(QRect(-1, 0, 251, 30))
        self.customerRefreshButton.setMinimumSize(QSize(200, 30))
        self.customerRefreshButton.setMaximumSize(QSize(16777215, 30))
        self.customerRefreshButton.setCheckable(False)
        self.customerRefreshButton.setChecked(False)
        self.customerRefreshButton.setAutoDefault(False)
        self.customerRefreshButton.setFlat(False)
        self.buttonScroller = QScrollArea(self.customertab)
        self.buttonScroller.setObjectName(u"buttonScroller")
        self.buttonScroller.setGeometry(QRect(-1, 30, 250, 659))
        sizePolicy2.setHeightForWidth(self.buttonScroller.sizePolicy().hasHeightForWidth())
        self.buttonScroller.setSizePolicy(sizePolicy2)
        self.buttonScroller.setMinimumSize(QSize(250, 0))
        self.buttonScroller.setMaximumSize(QSize(250, 1000))
        self.buttonScroller.setFrameShape(QFrame.NoFrame)
        self.buttonScroller.setFrameShadow(QFrame.Plain)
        self.buttonScroller.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.buttonScroller.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.buttonScroller.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.buttonScroller.setWidgetResizable(True)
        self.customerArea = QWidget()
        self.customerArea.setObjectName(u"customerArea")
        self.customerArea.setGeometry(QRect(0, 0, 229, 659))
        self.buttonScroller.setWidget(self.customerArea)
        self.searchBar = QLineEdit(self.customertab)
        self.searchBar.setObjectName(u"searchBar")
        self.searchBar.setGeometry(QRect(249, 0, 251, 30))
        sizePolicy.setHeightForWidth(self.searchBar.sizePolicy().hasHeightForWidth())
        self.searchBar.setSizePolicy(sizePolicy)
        self.searchBar.setMaximumSize(QSize(300, 30))
        self.searchBar.setClearButtonEnabled(True)
        self.Tabs.addTab(self.customertab, "")
        self.creatorTab = QWidget()
        self.creatorTab.setObjectName(u"creatorTab")
        self.customerSelection = QComboBox(self.creatorTab)
        self.customerSelection.setObjectName(u"customerSelection")
        self.customerSelection.setGeometry(QRect(0, 2, 260, 35))
        self.firstNameEnter = QLineEdit(self.creatorTab)
        self.firstNameEnter.setObjectName(u"firstNameEnter")
        self.firstNameEnter.setGeometry(QRect(0, 40, 131, 32))
        self.lastNameEnter = QLineEdit(self.creatorTab)
        self.lastNameEnter.setObjectName(u"lastNameEnter")
        self.lastNameEnter.setGeometry(QRect(130, 40, 131, 32))
        self.brandEnter = QLineEdit(self.creatorTab)
        self.brandEnter.setObjectName(u"brandEnter")
        self.brandEnter.setGeometry(QRect(0, 80, 101, 32))
        self.brandEnter.setClearButtonEnabled(False)
        self.itemDetailEnter = QLineEdit(self.creatorTab)
        self.itemDetailEnter.setObjectName(u"itemDetailEnter")
        self.itemDetailEnter.setGeometry(QRect(100, 80, 401, 32))
        self.extraDetailEnter = QPlainTextEdit(self.creatorTab)
        self.extraDetailEnter.setObjectName(u"extraDetailEnter")
        self.extraDetailEnter.setGeometry(QRect(0, 190, 501, 501))
        self.creationButton = QPushButton(self.creatorTab)
        self.creationButton.setObjectName(u"creationButton")
        self.creationButton.setGeometry(QRect(260, 0, 241, 71))
        self.contactEnter = QLineEdit(self.creatorTab)
        self.contactEnter.setObjectName(u"contactEnter")
        self.contactEnter.setGeometry(QRect(0, 150, 381, 32))
        self.dateEdit = QDateEdit(self.creatorTab)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(380, 150, 121, 32))
        self.dateEdit.setMaximumDate(QDate(9999, 11, 30))
        self.dateEdit.setCalendarPopup(True)
        self.label = QLabel(self.creatorTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(380, 130, 121, 18))
        self.Tabs.addTab(self.creatorTab, "")
        self.alerts = QWidget()
        self.alerts.setObjectName(u"alerts")
        self.alertScroller = QScrollArea(self.alerts)
        self.alertScroller.setObjectName(u"alertScroller")
        self.alertScroller.setGeometry(QRect(0, 70, 500, 613))
        self.alertScroller.setMinimumSize(QSize(500, 0))
        self.alertScroller.setMaximumSize(QSize(16777215, 1000))
        self.alertScroller.setFrameShadow(QFrame.Sunken)
        self.alertScroller.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.alertScroller.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.alertScroller.setWidgetResizable(False)
        self.alertButtonArea = QWidget()
        self.alertButtonArea.setObjectName(u"alertButtonArea")
        self.alertButtonArea.setGeometry(QRect(0, 0, 475, 609))
        self.alertScroller.setWidget(self.alertButtonArea)
        self.alertCustomer = QComboBox(self.alerts)
        self.alertCustomer.setObjectName(u"alertCustomer")
        self.alertCustomer.setGeometry(QRect(400, 35, 101, 35))
        self.alertCustomer.setFrame(True)
        self.createAlert = QPushButton(self.alerts)
        self.createAlert.setObjectName(u"createAlert")
        self.createAlert.setGeometry(QRect(400, 0, 101, 35))
        self.youHave = QLabel(self.alerts)
        self.youHave.setObjectName(u"youHave")
        self.youHave.setGeometry(QRect(0, 30, 61, 31))
        self.alertsLabel = QLabel(self.alerts)
        self.alertsLabel.setObjectName(u"alertsLabel")
        self.alertsLabel.setGeometry(QRect(60, 50, 121, 18))
        self.customerLabel = QLabel(self.alerts)
        self.customerLabel.setObjectName(u"customerLabel")
        self.customerLabel.setGeometry(QRect(60, 30, 121, 18))
        self.dateTimeEdit = QDateTimeEdit(self.alerts)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(200, 0, 190, 35))
        self.dateTimeEdit.setCalendarPopup(True)
        self.alertText = QLineEdit(self.alerts)
        self.alertText.setObjectName(u"alertText")
        self.alertText.setGeometry(QRect(200, 35, 190, 35))
        self.Tabs.addTab(self.alerts, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.Tabs.addTab(self.tab, "")
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), u"Solven'ts")
        QWidget.setTabOrder(self.Tabs, self.customerRefreshButton)
        QWidget.setTabOrder(self.customerRefreshButton, self.searchBar)
        QWidget.setTabOrder(self.searchBar, self.buttonScroller)
        QWidget.setTabOrder(self.buttonScroller, self.customerSelection)
        QWidget.setTabOrder(self.customerSelection, self.firstNameEnter)
        QWidget.setTabOrder(self.firstNameEnter, self.lastNameEnter)
        QWidget.setTabOrder(self.lastNameEnter, self.brandEnter)
        QWidget.setTabOrder(self.brandEnter, self.itemDetailEnter)
        QWidget.setTabOrder(self.itemDetailEnter, self.alertText)
        QWidget.setTabOrder(self.alertText, self.contactEnter)
        QWidget.setTabOrder(self.contactEnter, self.dateEdit)
        QWidget.setTabOrder(self.dateEdit, self.extraDetailEnter)
        QWidget.setTabOrder(self.extraDetailEnter, self.creationButton)
        QWidget.setTabOrder(self.creationButton, self.alertScroller)
        QWidget.setTabOrder(self.alertScroller, self.alertCustomer)
        QWidget.setTabOrder(self.alertCustomer, self.createAlert)
        QWidget.setTabOrder(self.createAlert, self.dateTimeEdit)
        QWidget.setTabOrder(self.dateTimeEdit, self.informationBrowser)

        self.retranslateUi(Main)

        self.Tabs.setCurrentIndex(0)
        self.customerRefreshButton.setDefault(False)


        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"Solven't | Problem Causing", None))
        self.informationBrowser.setHtml(QCoreApplication.translate("Main", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Noto Sans'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20pt;\"><br /></p></body></html>", None))
        self.informationBrowser.setPlaceholderText(QCoreApplication.translate("Main", u"Select a customer to view customer information", None))
#if QT_CONFIG(tooltip)
        self.customerRefreshButton.setToolTip(QCoreApplication.translate("Main", u"<html><head/><body><p>Refreshes the serverlist<br/>maybe Javier forgot something?</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.customerRefreshButton.setText(QCoreApplication.translate("Main", u"Refresh Customer List / Search", None))
#if QT_CONFIG(tooltip)
        self.searchBar.setToolTip(QCoreApplication.translate("Main", u"<html><head/><body><p>Search/Filter through your servers so that you can find the perfect server even faster!</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.searchBar.setInputMask("")
        self.searchBar.setText("")
        self.searchBar.setPlaceholderText(QCoreApplication.translate("Main", u"Query", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.customertab), QCoreApplication.translate("Main", u"Customer Information Portal", None))
        self.customerSelection.setPlaceholderText(QCoreApplication.translate("Main", u"Select Your Customer!", None))
        self.firstNameEnter.setText("")
        self.firstNameEnter.setPlaceholderText(QCoreApplication.translate("Main", u"First Name", None))
        self.lastNameEnter.setPlaceholderText(QCoreApplication.translate("Main", u"Last Name", None))
        self.brandEnter.setPlaceholderText(QCoreApplication.translate("Main", u"Item", None))
        self.itemDetailEnter.setPlaceholderText(QCoreApplication.translate("Main", u"Extra Item Details i.e. color, year, version", None))
        self.extraDetailEnter.setPlainText("")
        self.extraDetailEnter.setPlaceholderText(QCoreApplication.translate("Main", u"Extra Customer Information", None))
        self.creationButton.setText(QCoreApplication.translate("Main", u"Create Your Customer!\n"
"Or Update an Existing Customer", None))
        self.contactEnter.setPlaceholderText(QCoreApplication.translate("Main", u"Customer Contact Information [can put multiple sources]", None))
        self.dateEdit.setDisplayFormat(QCoreApplication.translate("Main", u"MM/dd/yyyy", None))
        self.label.setText(QCoreApplication.translate("Main", u"Customer Birthday", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.creatorTab), QCoreApplication.translate("Main", u"Customer Creator", None))
#if QT_CONFIG(tooltip)
        self.Tabs.setTabToolTip(self.Tabs.indexOf(self.creatorTab), QCoreApplication.translate("Main", u"The Custom Customer Creator Maker", None))
#endif // QT_CONFIG(tooltip)
        self.alertCustomer.setPlaceholderText(QCoreApplication.translate("Main", u"Customer", None))
        self.createAlert.setText(QCoreApplication.translate("Main", u"Create Alert", None))
        self.youHave.setText(QCoreApplication.translate("Main", u"You have:", None))
        self.alertsLabel.setText(QCoreApplication.translate("Main", u"0 Alerts", None))
        self.customerLabel.setText(QCoreApplication.translate("Main", u"0 Customers", None))
        self.alertText.setPlaceholderText(QCoreApplication.translate("Main", u"What is the alert for?", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.alerts), QCoreApplication.translate("Main", u"Alerts", None))
    # retranslateUi

